apiVersion: openliberty.io/v1beta1
kind: OpenLibertyApplication
metadata:
  name: appmod
spec:
  applicationImage: image-registry.openshift-image-registry.svc:5000/userNN-project/app-modernization:v1.0.0
  expose: true
  route:
    host: 'modresort.apps.atsocpd1.dmz'
    path: '/resorts'
